default_platform(:ios)

platform :ios do

	desc 'Push all staging builds to the TestFlight'
	lane :beta do

		slack(
			message: 'Process initiated: releasing iOS staging builds (' + Time.new.to_s + ')',
			slack_url: 'https://hooks.slack.com/services/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',
			default_payloads: []
		)

		['MT-SB-Stage', 'MT-SB-Stage'].each do |scheme|

			buildNumber = increment_build_number_in_plist(target: scheme)
			appVersion = get_version_number_from_plist(target: scheme)
	
			appIdentifier = get_product_bundle_id(project_filepath: '../ios/MT.xcodeproj', scheme: scheme)
	
			appName = get_info_plist_value(path: './' + scheme + '/' + scheme + '-Info.plist', key: 'CFBundleDisplayName')

			# match(type: 'appstore', app_identifier: appIdentifier)
			# gym(scheme: scheme)
			# pilot(username: 'eugene@theleanapps.com')

			slack(
				message: ' ' + appName + ' Released',
				slack_url: 'https://hooks.slack.com/services/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',
				payload: {
					'' => '',
					'○ Bundle ID' => appIdentifier,
					'○ Build Date' => Time.new.to_s,
					'○ Build Number' => buildNumber,
					'○ App Version' => appVersion,
				},
				default_payloads: [:last_git_commit]
			)

		end

		slack(
			message: 'Process finished: releasing iOS staging builds (' + Time.new.to_s + ')',
			slack_url: 'https://hooks.slack.com/services/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',
			default_payloads: []
		)

	end

	# after_all do |lane|
	# 	slack(
	# 		message: 'Successfully deployed new app'
	# 	)

	# error do |lane, exception|
	# 	slack(
	# 		message: exception.message,
	# 		success: false
	# 	)
end
